//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localisation.Loc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localisation.Loc.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändere Sprache.
        /// </summary>
        public static string Btn_Content {
            get {
                return ResourceManager.GetString("Btn_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute ist ein schöner Tag!.
        /// </summary>
        public static string Tbl_Text {
            get {
                return ResourceManager.GetString("Tbl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eins.
        /// </summary>
        public static string TestEnum_1 {
            get {
                return ResourceManager.GetString("TestEnum_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwei.
        /// </summary>
        public static string TestEnum_2 {
            get {
                return ResourceManager.GetString("TestEnum_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drei.
        /// </summary>
        public static string TestEnum_3 {
            get {
                return ResourceManager.GetString("TestEnum_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vier.
        /// </summary>
        public static string TestEnum_4 {
            get {
                return ResourceManager.GetString("TestEnum_4", resourceCulture);
            }
        }
    }
}
